[dependencies.caffe2-imports]
path = "../caffe2-imports"
[dependencies.caffe2-operator]
path = "../caffe2-operator"
[dependencies.caffe2-context]
path = "../caffe2-context"
[package]
edition = "2021"
name = "caffe2op-sinh"
version = "0.1.0"
