[dependencies.caffe2-imports]
path = "../caffe2-imports"
[dependencies.caffe2-operator]
path = "../caffe2-operator"
[dependencies.caffe2-types]
path = "../caffe2-types"
[package]
edition = "2021"
name = "caffe2op-im2col"
version = "0.1.0"