[dependencies.caffe2-derive]
path = "../caffe2-derive"
[dependencies.caffe2-tensor]
path = "../caffe2-tensor"
[dependencies.caffe2-imports]
path = "../caffe2-imports"
[package]
edition = "2021"
name = "caffe2-packed-linear-weight"
version = "0.1.0"
